/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InvoiceTrackingSystem;

import CorePackage.Address;
import CorePackage.City;
import CorePackage.Customer;
import CorePackage.Neighborhood;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 90554
 */
public class AddressScreen extends javax.swing.JFrame {

    private Customer customer;
    private Address address;
    private boolean isUpdateMode;

    public AddressScreen() {
        initComponents();
        ImageIcon icon1 = new ImageIcon("C:\\Users\\bayra\\Downloads\\Address.png");
        Image img1 = icon1.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        icon1.setImage(img1);
        AddressLabel.setIcon(icon1);
    }

    public AddressScreen(Customer customer) {
        this.customer = customer;
        this.address = null;
        this.isUpdateMode = false;
        initComponents();
        loadCities();
        AddChangeBttn.setText("Add");
    }

    public AddressScreen(Customer customer, Address address) {
        this.customer = customer;
        this.address = address;
        this.isUpdateMode = address != null;
        initComponents();
        loadCities();

        if (isUpdateMode) {
            populateAddressDetails(); 
            AddChangeBttn.setText("Update");
        } else {
            AddChangeBttn.setText("Add");
        }
    }

    private void loadCities() {
        CityComboBox.removeAllItems();
        List<City> cities = City.getAllCities();
        for (City city : cities) {
            CityComboBox.addItem(city.getCityName());
        }
    }

    private void loadNeighborhoods() {
        NeighbourComboBox.removeAllItems();
        String selectedCity = (String) CityComboBox.getSelectedItem();
        if (selectedCity != null) {
            List<Neighborhood> neighborhoods = Neighborhood.getNeighborhoodsByCityName(selectedCity);
            for (Neighborhood neighborhood : neighborhoods) {
                NeighbourComboBox.addItem(neighborhood.getNeighborhoodName());
            }
        }
    }

    private void populateAddressDetails() {
        AddressNameTextField.setText(address.getAddressName());
        OpenAddressTextField.setText(address.getOpenAddress());

        String cityName = City.getCityNameById(address.getNeighborhood().getCityId());
        if (cityName != null) {
            CityComboBox.setSelectedItem(cityName);
        }

        loadNeighborhoods();
        NeighbourComboBox.setSelectedItem(address.getNeighborhood().getNeighborhoodName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddressLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AddressNameLabel = new javax.swing.JLabel();
        AddressNameTextField = new javax.swing.JTextField();
        CityComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        NeighbourComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OpenAddressTextField = new javax.swing.JTextField();
        AddChangeBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 44));

        AddressLabel.setFont(new java.awt.Font("SimSun-ExtG", 1, 24)); // NOI18N
        AddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressLabel.setText("ADDRES");
        AddressLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AddressNameLabel.setFont(new java.awt.Font("SimSun-ExtG", 1, 12)); // NOI18N
        AddressNameLabel.setText("Address Name:");

        CityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 1, 12)); // NOI18N
        jLabel1.setText("City:");

        jLabel2.setFont(new java.awt.Font("SimSun-ExtG", 1, 12)); // NOI18N
        jLabel2.setText("Neighbour:");

        jLabel3.setFont(new java.awt.Font("SimSun-ExtG", 1, 12)); // NOI18N
        jLabel3.setText("Open Address");

        AddChangeBttn.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        AddChangeBttn.setText("Add");
        AddChangeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddChangeBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OpenAddressTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AddressNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NeighbourComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddChangeBttn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NeighbourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OpenAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(AddChangeBttn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(AddressLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddChangeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddChangeBttnActionPerformed
        String addressName = AddressNameTextField.getText().trim();
        String openAddress = OpenAddressTextField.getText().trim();
        String cityName = (String) CityComboBox.getSelectedItem();
        String neighborhoodName = (String) NeighbourComboBox.getSelectedItem();

        if (addressName.isEmpty() || openAddress.isEmpty() || cityName == null || neighborhoodName == null) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!");
            return;
        }

        int neighborhoodId = Neighborhood.getNeighborhoodIdByNameAndCity(neighborhoodName, cityName);
        if (neighborhoodId == 0) {
            JOptionPane.showMessageDialog(this, "Invalid neighborhood or city selected!");
            return;
        }

        if (isUpdateMode) {
            address.setAddressName(addressName);
            address.setOpenAddress(openAddress);
            address.getNeighborhood().setNeighborhoodId(neighborhoodId);
            Address.updateAddress(address, neighborhoodId);
            JOptionPane.showMessageDialog(this, "Address updated successfully!");
        } else {
            Address newAddress = new Address(0, addressName, openAddress, new Neighborhood(neighborhoodId, neighborhoodName, 0));
            customer.addAddress(newAddress, neighborhoodId);
            JOptionPane.showMessageDialog(this, "Address added successfully!");
        }

        dispose();
        new CustomerInformationScreen(customer).setVisible(true);
    }//GEN-LAST:event_AddChangeBttnActionPerformed

    private void CityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityComboBoxActionPerformed
        loadNeighborhoods();
    }//GEN-LAST:event_CityComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddressScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddChangeBttn;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel AddressNameLabel;
    private javax.swing.JTextField AddressNameTextField;
    private javax.swing.JComboBox<String> CityComboBox;
    private javax.swing.JComboBox<String> NeighbourComboBox;
    private javax.swing.JTextField OpenAddressTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
