/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InvoiceTrackingSystem;

/**
 *
 * @author bayra
 */
public class AdminSideBar extends javax.swing.JFrame {

    /**
     * Creates new form AdminSideBar
     */
    public AdminSideBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UsersButton = new javax.swing.JButton();
        RequestButton = new javax.swing.JButton();
        InterruptsButton = new javax.swing.JButton();
        AnnouncementsButton = new javax.swing.JButton();
        SubscriptionsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UsersButton1 = new javax.swing.JButton();
        RequestButton1 = new javax.swing.JButton();
        InterruptsButton1 = new javax.swing.JButton();
        AnnouncementsButton1 = new javax.swing.JButton();
        SubscriptionsButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        UsersButton2 = new javax.swing.JButton();
        RequestButton2 = new javax.swing.JButton();
        InterruptsButton2 = new javax.swing.JButton();
        AnnouncementsButton2 = new javax.swing.JButton();
        SubscriptionsButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SettingsLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UsersSideBar = new javax.swing.JLabel();
        RequestsSideBar = new javax.swing.JLabel();
        InterruptsSideBar = new javax.swing.JLabel();
        SubscriptionsSideBar = new javax.swing.JLabel();
        AnnouncementsSideBar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POWER FLOW");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        UsersButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        UsersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UserIcon.png"))); // NOI18N
        UsersButton.setText("Users");
        UsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersButtonActionPerformed(evt);
            }
        });

        RequestButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        RequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RequestService.png"))); // NOI18N
        RequestButton.setText("Requests");
        RequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestButtonActionPerformed(evt);
            }
        });

        InterruptsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Interrupts.png"))); // NOI18N
        InterruptsButton.setText("Interrupts");

        AnnouncementsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Announcements.png"))); // NOI18N
        AnnouncementsButton.setText("Announcements");

        SubscriptionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Subscriptions.png"))); // NOI18N
        SubscriptionsButton.setText("Subscriptions");

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("POWER FLOW");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        UsersButton1.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        UsersButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UserIcon.png"))); // NOI18N
        UsersButton1.setText("Users");
        UsersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersButton1ActionPerformed(evt);
            }
        });

        RequestButton1.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        RequestButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RequestService.png"))); // NOI18N
        RequestButton1.setText("Requests");
        RequestButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestButton1ActionPerformed(evt);
            }
        });

        InterruptsButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Interrupts.png"))); // NOI18N
        InterruptsButton1.setText("Interrupts");

        AnnouncementsButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Announcements.png"))); // NOI18N
        AnnouncementsButton1.setText("Announcements");

        SubscriptionsButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Subscriptions.png"))); // NOI18N
        SubscriptionsButton1.setText("Subscriptions");

        jLabel5.setFont(new java.awt.Font("SimSun-ExtG", 2, 12)); // NOI18N
        jLabel5.setText("Made by PowerFlow");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 44));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("POWER FLOW");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        UsersButton2.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        UsersButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UserIcon.png"))); // NOI18N
        UsersButton2.setText("Users");
        UsersButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersButton2ActionPerformed(evt);
            }
        });

        RequestButton2.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        RequestButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RequestService.png"))); // NOI18N
        RequestButton2.setText("Requests");
        RequestButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestButton2ActionPerformed(evt);
            }
        });

        InterruptsButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Interrupts.png"))); // NOI18N
        InterruptsButton2.setText("Interrupts");

        AnnouncementsButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Announcements.png"))); // NOI18N
        AnnouncementsButton2.setText("Announcements");

        SubscriptionsButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Subscriptions.png"))); // NOI18N
        SubscriptionsButton2.setText("Subscriptions");

        jPanel2.setBackground(new java.awt.Color(34, 40, 44));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu30.png"))); // NOI18N

        SettingsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Settings.png"))); // NOI18N
        SettingsLabel.setText("Settings");

        jLabel6.setFont(new java.awt.Font("SimSun-ExtG", 2, 12)); // NOI18N
        jLabel6.setText("Made by PowerFlow");

        UsersSideBar.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        UsersSideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UserIcon.png"))); // NOI18N
        UsersSideBar.setText("     Users");
        UsersSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersSideBarMouseClicked(evt);
            }
        });

        RequestsSideBar.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        RequestsSideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/RequestService.png"))); // NOI18N
        RequestsSideBar.setText("     Requests");

        InterruptsSideBar.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        InterruptsSideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Interrupts.png"))); // NOI18N
        InterruptsSideBar.setText("   Interrupts");

        SubscriptionsSideBar.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        SubscriptionsSideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Subscriptions.png"))); // NOI18N
        SubscriptionsSideBar.setText("       Subscriptions");

        AnnouncementsSideBar.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        AnnouncementsSideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Announcements.png"))); // NOI18N
        AnnouncementsSideBar.setText("   Announcements");

        jLabel12.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Resized_logo_50x50.png"))); // NOI18N
        jLabel12.setText(" POWER FLOW");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InterruptsSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubscriptionsSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsersSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnnouncementsSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RequestsSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(SettingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(UsersSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RequestsSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InterruptsSideBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubscriptionsSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnnouncementsSideBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SettingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(SubscriptionsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(AnnouncementsButton2)
                        .addGap(75, 75, 75))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(UsersButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(RequestButton2)
                            .addGap(51, 51, 51)
                            .addComponent(InterruptsButton2))))
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InterruptsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RequestButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsersButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnnouncementsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubscriptionsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersButtonActionPerformed
        //        JButton UserButton = new JButton("Users");
        //        Image img = new ImageIcon(this.getClass().getResource("/Icons/UserIcon.png")).getImage();
        //        UserButton.setBounds(174,32,185,81);
        //        contentPane.add(UserButton);
    }//GEN-LAST:event_UsersButtonActionPerformed

    private void RequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestButtonActionPerformed

    private void UsersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersButton1ActionPerformed
        //        JButton UserButton = new JButton("Users");
        //        Image img = new ImageIcon(this.getClass().getResource("/Icons/UserIcon.png")).getImage();
        //        UserButton.setBounds(174,32,185,81);
        //        contentPane.add(UserButton);
    }//GEN-LAST:event_UsersButton1ActionPerformed

    private void RequestButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestButton1ActionPerformed

    private void UsersButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersButton2ActionPerformed
        //        JButton UserButton = new JButton("Users");
        //        Image img = new ImageIcon(this.getClass().getResource("/Icons/UserIcon.png")).getImage();
        //        UserButton.setBounds(174,32,185,81);
        //        contentPane.add(UserButton);
    }//GEN-LAST:event_UsersButton2ActionPerformed

    private void RequestButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestButton2ActionPerformed

    private void UsersSideBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersSideBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UsersSideBarMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSideBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSideBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSideBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSideBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSideBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnouncementsButton;
    private javax.swing.JButton AnnouncementsButton1;
    private javax.swing.JButton AnnouncementsButton2;
    private javax.swing.JLabel AnnouncementsSideBar;
    private javax.swing.JButton InterruptsButton;
    private javax.swing.JButton InterruptsButton1;
    private javax.swing.JButton InterruptsButton2;
    private javax.swing.JLabel InterruptsSideBar;
    private javax.swing.JButton RequestButton;
    private javax.swing.JButton RequestButton1;
    private javax.swing.JButton RequestButton2;
    private javax.swing.JLabel RequestsSideBar;
    private javax.swing.JLabel SettingsLabel;
    private javax.swing.JButton SubscriptionsButton;
    private javax.swing.JButton SubscriptionsButton1;
    private javax.swing.JButton SubscriptionsButton2;
    private javax.swing.JLabel SubscriptionsSideBar;
    private javax.swing.JButton UsersButton;
    private javax.swing.JButton UsersButton1;
    private javax.swing.JButton UsersButton2;
    private javax.swing.JLabel UsersSideBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
