/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InvoiceTrackingSystem;

/**
 *
 * @author 90554
 */
public class CustomerInformationScreen extends javax.swing.JFrame {

    /**
     * Creates new form CustomerInformationScreen
     */
    public CustomerInformationScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NationalIdLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressList = new javax.swing.JList<>();
        AddressLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        DeleteAddressButton = new javax.swing.JButton();
        UsernameTextField = new javax.swing.JTextField();
        PhoneTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        AddAddressButton = new javax.swing.JButton();
        ChangeAddressBttn = new javax.swing.JButton();
        SurnameTextField = new javax.swing.JTextField();
        NameTextField2 = new javax.swing.JTextField();
        ChangePasswordBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 44));
        jPanel1.setPreferredSize(new java.awt.Dimension(965, 657));
        jPanel1.setLayout(null);

        MenuButton.setText("Menu");
        jPanel1.add(MenuButton);
        MenuButton.setBounds(6, 6, 60, 23);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERSONAL INFORMATION");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(146, 63, 669, 41);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name - Surname:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 50, 158, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Username:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 90, 158, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("National ID Number:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 130, 230, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Addresses");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(70, 265, 158, 20);

        NationalIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NationalIdLabel.setText("jLabel5");
        jPanel2.add(NationalIdLabel);
        NationalIdLabel.setBounds(330, 130, 291, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 170, 158, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 210, 158, 20);

        AddressList.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AddressList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(AddressList);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(70, 299, 230, 110);

        AddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddressLabel.setText("jLabel8");
        jPanel2.add(AddressLabel);
        AddressLabel.setBounds(330, 300, 290, 100);

        SaveButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SaveButton.setText("Save");
        jPanel2.add(SaveButton);
        SaveButton.setBounds(590, 500, 72, 32);

        DeleteAddressButton.setText("Delete Address");
        jPanel2.add(DeleteAddressButton);
        DeleteAddressButton.setBounds(498, 430, 120, 23);

        UsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameTextField.setText("jTextField2");
        jPanel2.add(UsernameTextField);
        UsernameTextField.setBounds(330, 87, 291, 20);

        PhoneTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PhoneTextField.setText("jTextField3");
        jPanel2.add(PhoneTextField);
        PhoneTextField.setBounds(330, 170, 291, 20);

        EmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailTextField.setText("jTextField4");
        jPanel2.add(EmailTextField);
        EmailTextField.setBounds(330, 210, 291, 20);

        AddAddressButton.setText("Add Address");
        jPanel2.add(AddAddressButton);
        AddAddressButton.setBounds(70, 430, 120, 23);

        ChangeAddressBttn.setText("Change Address");
        jPanel2.add(ChangeAddressBttn);
        ChangeAddressBttn.setBounds(370, 430, 120, 23);

        SurnameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SurnameTextField.setText("jTextField1");
        jPanel2.add(SurnameTextField);
        SurnameTextField.setBounds(490, 50, 130, 20);

        NameTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NameTextField2.setText("jTextField1");
        NameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(NameTextField2);
        NameTextField2.setBounds(330, 50, 150, 20);

        ChangePasswordBttn.setText("Change Password");
        jPanel2.add(ChangePasswordBttn);
        ChangePasswordBttn.setBounds(70, 510, 130, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(146, 122, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInformationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInformationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInformationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInformationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInformationScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAddressButton;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JList<String> AddressList;
    private javax.swing.JButton ChangeAddressBttn;
    private javax.swing.JButton ChangePasswordBttn;
    private javax.swing.JButton DeleteAddressButton;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JButton MenuButton;
    private javax.swing.JTextField NameTextField2;
    private javax.swing.JLabel NationalIdLabel;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField SurnameTextField;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
