/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InvoiceTrackingSystem;

/**
 *
 * @author bayra
 */
public class CustomerAnnouncementsScreen extends javax.swing.JFrame {

    /**
     * Creates new form AnnouncementsScreen
     */
    public CustomerAnnouncementsScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AnnouncementsTable = new javax.swing.JTable();

        MenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu30.png"))); // NOI18N
        MenuButton.setPreferredSize(new java.awt.Dimension(36, 36));
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 44));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Announcements.png"))); // NOI18N
        jLabel1.setText("  ANNOUNCEMENTS");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MenuButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu30.png"))); // NOI18N
        MenuButton1.setPreferredSize(new java.awt.Dimension(36, 36));
        MenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButton1ActionPerformed(evt);
            }
        });

        AnnouncementsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Announcements"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AnnouncementsTable);
        if (AnnouncementsTable.getColumnModel().getColumnCount() > 0) {
            AnnouncementsTable.getColumnModel().getColumn(0).setMinWidth(65);
            AnnouncementsTable.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        //        // Kaynağı yükle
        //        URL resourceURL = this.getClass().getResource("/Icons/MenulIcon.png");
        //        if (resourceURL == null) {
            //            System.out.println("Kaynak dosyası bulunamadı!");
            //        } else {
            //            System.out.println("Kaynak dosyası bulundu: " + resourceURL.toExternalForm());
            //        }
        //        InputStream is = getClass().getResourceAsStream("/Icons/MenulIcon.png");
        //        if (is == null) {
            //            JOptionPane.showMessageDialog(this, "Kaynak dosyası bulunamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
            //        } else {
            //            Image img = null;
            //            try {
                //                img = new ImageIcon(ImageIO.read(is)).getImage();
                //            } catch (IOException ex) {
                //                Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //            JButton btnNewButton = new JButton(new ImageIcon(img));
            //            contentPane.add(btnNewButton);
            //            contentPane.revalidate();
            //            contentPane.repaint();
            //        }
        //
        //        // Resmi yükle ve boyutlandır
        //        Image img = new ImageIcon(resourceURL).getImage();
        //        Image scaledImg = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // 50x50 boyutunda
        //
        //        // Buton oluştur ve ikon ekle
        //        JButton MenuButton = new JButton();
        //        MenuButton.setIcon(new ImageIcon(scaledImg));
        //        MenuButton.setBounds(100, 100, 100, 100); // Daha büyük boyut
        //        MenuButton.setBackground(Color.WHITE); // Arka planı değiştir
        //
        //        // Butonu ekle
        //        contentPane.add(MenuButton);
        //
        //        // Görünümü yenile
        //        contentPane.revalidate();
        //        contentPane.repaint();
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void MenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButton1ActionPerformed
        //        // Kaynağı yükle
        //        URL resourceURL = this.getClass().getResource("/Icons/MenulIcon.png");
        //        if (resourceURL == null) {
            //            System.out.println("Kaynak dosyası bulunamadı!");
            //        } else {
            //            System.out.println("Kaynak dosyası bulundu: " + resourceURL.toExternalForm());
            //        }
        //        InputStream is = getClass().getResourceAsStream("/Icons/MenulIcon.png");
        //        if (is == null) {
            //            JOptionPane.showMessageDialog(this, "Kaynak dosyası bulunamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
            //        } else {
            //            Image img = null;
            //            try {
                //                img = new ImageIcon(ImageIO.read(is)).getImage();
                //            } catch (IOException ex) {
                //                Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //            JButton btnNewButton = new JButton(new ImageIcon(img));
            //            contentPane.add(btnNewButton);
            //            contentPane.revalidate();
            //            contentPane.repaint();
            //        }
        //
        //        // Resmi yükle ve boyutlandır
        //        Image img = new ImageIcon(resourceURL).getImage();
        //        Image scaledImg = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // 50x50 boyutunda
        //
        //        // Buton oluştur ve ikon ekle
        //        JButton MenuButton = new JButton();
        //        MenuButton.setIcon(new ImageIcon(scaledImg));
        //        MenuButton.setBounds(100, 100, 100, 100); // Daha büyük boyut
        //        MenuButton.setBackground(Color.WHITE); // Arka planı değiştir
        //
        //        // Butonu ekle
        //        contentPane.add(MenuButton);
        //
        //        // Görünümü yenile
        //        contentPane.revalidate();
        //        contentPane.repaint();
    }//GEN-LAST:event_MenuButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAnnouncementsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAnnouncementsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAnnouncementsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAnnouncementsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerAnnouncementsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AnnouncementsTable;
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton MenuButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
