/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InvoiceTrackingSystem;
import CorePackage.Admin;
import CorePackage.Customer;
import CorePackage.Database;
import CorePackage.User;
import InvoiceTrackingSystem.StartScreen;
import javax.swing.JOptionPane;

/**
 *
 * @author bayra
 */
public class InterruptionScreen extends javax.swing.JFrame {

    /**
     * Creates new form InterruptionScreen
     */
    public InterruptionScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AdminAnnouncementsPanel = new javax.swing.JPanel();
        neighbourhoodjComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MenuButton = new javax.swing.JButton();
        CityjComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        userIDjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MakeInterrupt = new javax.swing.JButton();
        RemoveInterrupt = new javax.swing.JButton();
        ElectricityjRadioButton = new javax.swing.JRadioButton();
        waterjRadioButton = new javax.swing.JRadioButton();
        NaturalGasjRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminAnnouncementsPanel.setBackground(new java.awt.Color(34, 40, 44));

        neighbourhoodjComboBox.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        jLabel1.setText("Neighbourhood:");

        jLabel2.setFont(new java.awt.Font("SimSun-ExtG", 2, 10)); // NOI18N
        jLabel2.setText("*Please choose which service will be interrupted?");

        jLabel5.setFont(new java.awt.Font("SimSun-ExtG", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INTERRUPTION");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setFont(new java.awt.Font("SimSun-ExtG", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        MenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu30.png"))); // NOI18N
        MenuButton.setPreferredSize(new java.awt.Dimension(36, 36));
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });

        CityjComboBox.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        jLabel3.setText("City:");

        userIDjTextField.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        jLabel4.setText("Customer ID:");

        MakeInterrupt.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        MakeInterrupt.setText("Make Interrupt");
        MakeInterrupt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeInterruptActionPerformed(evt);
            }
        });

        RemoveInterrupt.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        RemoveInterrupt.setText("Remove Interrupt");
        RemoveInterrupt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveInterruptActionPerformed(evt);
            }
        });

        ElectricityjRadioButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        ElectricityjRadioButton.setText("Electricity");

        waterjRadioButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        waterjRadioButton.setText("Water");

        NaturalGasjRadioButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        NaturalGasjRadioButton.setText("Natural Gas");

        jLabel6.setFont(new java.awt.Font("SimSun-ExtG", 2, 10)); // NOI18N
        jLabel6.setText("*Please select the topic of your announcements.");

        javax.swing.GroupLayout AdminAnnouncementsPanelLayout = new javax.swing.GroupLayout(AdminAnnouncementsPanel);
        AdminAnnouncementsPanel.setLayout(AdminAnnouncementsPanelLayout);
        AdminAnnouncementsPanelLayout.setHorizontalGroup(
            AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminAnnouncementsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(58, 58, 58))
            .addGroup(AdminAnnouncementsPanelLayout.createSequentialGroup()
                .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(AdminAnnouncementsPanelLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MakeInterrupt)
                            .addGap(25, 25, 25)
                            .addComponent(RemoveInterrupt))
                        .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdminAnnouncementsPanelLayout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AdminAnnouncementsPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(userIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminAnnouncementsPanelLayout.createSequentialGroup()
                                            .addComponent(ElectricityjRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(waterjRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(NaturalGasjRadioButton))
                                        .addGroup(AdminAnnouncementsPanelLayout.createSequentialGroup()
                                            .addComponent(CityjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(neighbourhoodjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(AdminAnnouncementsPanelLayout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AdminAnnouncementsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminAnnouncementsPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        AdminAnnouncementsPanelLayout.setVerticalGroup(
            AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminAnnouncementsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElectricityjRadioButton)
                    .addComponent(waterjRadioButton)
                    .addComponent(NaturalGasjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neighbourhoodjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CityjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(userIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MakeInterrupt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveInterrupt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(AdminAnnouncementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminAnnouncementsPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminAnnouncementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminAnnouncementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        //        // Kaynağı yükle
        //        URL resourceURL = this.getClass().getResource("/Icons/MenulIcon.png");
        //        if (resourceURL == null) {
            //            System.out.println("Kaynak dosyası bulunamadı!");
            //        } else {
            //            System.out.println("Kaynak dosyası bulundu: " + resourceURL.toExternalForm());
            //        }
        //        InputStream is = getClass().getResourceAsStream("/Icons/MenulIcon.png");
        //        if (is == null) {
            //            JOptionPane.showMessageDialog(this, "Kaynak dosyası bulunamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
            //        } else {
            //            Image img = null;
            //            try {
                //                img = new ImageIcon(ImageIO.read(is)).getImage();
                //            } catch (IOException ex) {
                //                Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //            JButton btnNewButton = new JButton(new ImageIcon(img));
            //            contentPane.add(btnNewButton);
            //            contentPane.revalidate();
            //            contentPane.repaint();
            //        }
        //
        //        // Resmi yükle ve boyutlandır
        //        Image img = new ImageIcon(resourceURL).getImage();
        //        Image scaledImg = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // 50x50 boyutunda
        //
        //        // Buton oluştur ve ikon ekle
        //        JButton MenuButton = new JButton();
        //        MenuButton.setIcon(new ImageIcon(scaledImg));
        //        MenuButton.setBounds(100, 100, 100, 100); // Daha büyük boyut
        //        MenuButton.setBackground(Color.WHITE); // Arka planı değiştir
        //
        //        // Butonu ekle
        //        contentPane.add(MenuButton);
        //
        //        // Görünümü yenile
        //        contentPane.revalidate();
        //        contentPane.repaint();
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed

    }//GEN-LAST:event_SignInButtonActionPerformed

    private void SignInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveInterruptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterruptionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterruptionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterruptionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterruptionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterruptionScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminAnnouncementsPanel;
    private javax.swing.JComboBox<String> CityjComboBox;
    private javax.swing.JRadioButton ElectricityjRadioButton;
    private javax.swing.JButton MakeInterrupt;
    private javax.swing.JButton MenuButton;
    private javax.swing.JRadioButton NaturalGasjRadioButton;
    private javax.swing.JButton RemoveInterrupt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> neighbourhoodjComboBox;
    private javax.swing.JTextField userIDjTextField;
    private javax.swing.JRadioButton waterjRadioButton;
    // End of variables declaration//GEN-END:variables
}
