package InvoiceTrackingSystem;

import CorePackage.Admin;
import CorePackage.Customer;
import CorePackage.User;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.SwingUtilities;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author sare
 */
public class StartScreen extends javax.swing.JFrame {

    public static User account;

    private ButtonGroup userTypeGroup;

    public StartScreen() {
        initComponents();
        setupFrame();
        NameSurnameLabel.setVisible(false);
        NameTextField.setVisible(false);
        SurnameTextField.setVisible(false);
        UsernameLabel.setVisible(false);
        UsernameTextField.setVisible(false);
        PasswordLabel.setVisible(false);
        PasswordTextField.setVisible(false);
        PhoneNumberLabel.setVisible(false);
        PhoneNoTextField.setVisible(false);
        IDNumberLabel.setVisible(false);
        IDNumberTextField.setVisible(false);

        ButtonGroup userTypeGroup = new ButtonGroup();
        userTypeGroup.add(AdminButton);
        userTypeGroup.add(CustomerButton);

    }

    private void setupFrame() {
        int newWidth = 965;
        int newHeight = 657;
        setTitle("Logo Ekranı");
        setSize(newWidth, newHeight);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        StartPanel.setPreferredSize(new Dimension(965, 657));
        StartPanel.setBackground(new Color(34, 40, 44));

        StartPanel.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        StartPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        SignUpPanel = new javax.swing.JPanel();
        SignUpLabel = new javax.swing.JLabel();
        NameSurnameLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        SurnameTextField = new javax.swing.JTextField();
        UsernameTextField = new javax.swing.JTextField();
        PhoneNoTextField = new javax.swing.JTextField();
        SignUpButton = new javax.swing.JButton();
        IDNumberLabel = new javax.swing.JLabel();
        IDNumberTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        NameTextField = new javax.swing.JTextField();
        AccTypeLabel = new javax.swing.JLabel();
        AdminButton = new javax.swing.JRadioButton();
        CustomerButton = new javax.swing.JRadioButton();
        SignInLayeredPanel = new javax.swing.JLayeredPane();
        SignInLabel = new javax.swing.JLabel();
        UsernameLabel1 = new javax.swing.JLabel();
        UsernameSignInTextField = new javax.swing.JTextField();
        PasswordLabel1 = new javax.swing.JLabel();
        SignInButton = new javax.swing.JButton();
        PasswordSignInTextField = new javax.swing.JPasswordField();
        LogoLabel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("POWER FLOW");
        jTextArea1.setSelectedTextColor(new java.awt.Color(0, 0, 51));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartPanel.setBackground(new java.awt.Color(34, 40, 44));
        StartPanel.setPreferredSize(new java.awt.Dimension(965, 657));
        StartPanel.setLayout(null);

        jLabel1.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 75, 96));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POWER FLOW");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StartPanel.add(jLabel1);
        jLabel1.setBounds(220, 60, 549, 82);

        SignUpPanel.setBackground(new java.awt.Color(44, 47, 50));

        SignUpLabel.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        SignUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpLabel.setText("SIGN UP");

        NameSurnameLabel.setText("Name Surname");

        UsernameLabel.setText("Username");

        PasswordLabel.setText("Password");

        PhoneNumberLabel.setText("Phone Number");

        SurnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurnameTextFieldActionPerformed(evt);
            }
        });

        SignUpButton.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        IDNumberLabel.setText("National ID Number");

        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        AccTypeLabel.setText("Account Type");

        AdminButton.setText("Admin");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });

        CustomerButton.setText("Customer");
        CustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUpPanelLayout = new javax.swing.GroupLayout(SignUpPanel);
        SignUpPanel.setLayout(SignUpPanelLayout);
        SignUpPanelLayout.setHorizontalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SignUpPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NameSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SignUpPanelLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SignUpPanelLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AccTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PhoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                                        .addComponent(AdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        SignUpPanelLayout.setVerticalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AccTypeLabel)
                .addGap(4, 4, 4)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerButton)
                    .addComponent(AdminButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameSurnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(PhoneNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PhoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpButton)
                .addGap(12, 12, 12))
        );

        SignInLayeredPanel.setBackground(new java.awt.Color(43, 46, 49));
        SignInLayeredPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SignInLabel.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        SignInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInLabel.setText("SIGN IN");

        UsernameLabel1.setText("Username");

        PasswordLabel1.setText("Password");

        SignInButton.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        SignInButton.setText("Sign In");
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });

        SignInLayeredPanel.setLayer(SignInLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SignInLayeredPanel.setLayer(UsernameLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SignInLayeredPanel.setLayer(UsernameSignInTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SignInLayeredPanel.setLayer(PasswordLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SignInLayeredPanel.setLayer(SignInButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SignInLayeredPanel.setLayer(PasswordSignInTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout SignInLayeredPanelLayout = new javax.swing.GroupLayout(SignInLayeredPanel);
        SignInLayeredPanel.setLayout(SignInLayeredPanelLayout);
        SignInLayeredPanelLayout.setHorizontalGroup(
            SignInLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInLayeredPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(SignInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignInLayeredPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(SignInLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(UsernameSignInTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignInLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordSignInTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        SignInLayeredPanelLayout.setVerticalGroup(
            SignInLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInLayeredPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(SignInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(UsernameLabel1)
                .addGap(18, 18, 18)
                .addComponent(UsernameSignInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(PasswordLabel1)
                .addGap(18, 18, 18)
                .addComponent(PasswordSignInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(SignInButton)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(SignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignInLayeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(SignInLayeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        StartPanel.add(jPanel1);
        jPanel1.setBounds(30, 170, 905, 423);
        StartPanel.add(LogoLabel);
        LogoLabel.setBounds(83, 54, 181, 156);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SurnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurnameTextFieldActionPerformed

    private void CustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerButtonActionPerformed
        NameSurnameLabel.setVisible(true);
        NameTextField.setVisible(true);
        SurnameTextField.setVisible(true);
        UsernameLabel.setVisible(true);
        UsernameTextField.setVisible(true);
        PasswordLabel.setVisible(true);
        PasswordTextField.setVisible(true);
        PhoneNumberLabel.setVisible(true);
        PhoneNoTextField.setVisible(true);
        IDNumberLabel.setVisible(true);
        IDNumberTextField.setVisible(true);
        JOptionPane.showMessageDialog(this, "Customer account selected!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CustomerButtonActionPerformed

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        if (UsernameSignInTextField.getText().equals("") || PasswordSignInTextField.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Fill All Entries.", "Failure", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            User u = new User();
            if (!u.isUsernameExists(UsernameSignInTextField.getText())) {
                JOptionPane.showMessageDialog(this, "This user doesn't exist!", "Failure", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (!u.isCredentialsValid(UsernameSignInTextField.getText(), PasswordSignInTextField.getText())) {
                JOptionPane.showMessageDialog(this, "Invalid credentials!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (u.isAdmin(UsernameSignInTextField.getText())) {
                Admin admin = new Admin();
                admin.setUsername(UsernameSignInTextField.getText());
                admin.setPassword(String.valueOf(PasswordSignInTextField.getPassword()));

                AdminScreen adminScreen = new AdminScreen(admin);
                adminScreen.setVisible(true);
                this.dispose();
            } else if (u.isCustomer(UsernameSignInTextField.getText())) {
                JOptionPane.showMessageDialog(this, "Welcome Customer!", "Success", JOptionPane.INFORMATION_MESSAGE);

                Customer customer = new Customer();
                customer.setUsername(UsernameSignInTextField.getText());
                CustomerScreen customerScreen = new CustomerScreen(customer);
                customerScreen.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_SignInButtonActionPerformed


    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        char[] passwordChars = PasswordTextField.getPassword();
        String password = new String(passwordChars);

        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";

        if (password.matches(regex)) {
            JOptionPane.showMessageDialog(this, "Valid Password!", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Password! Password must be at least 8 characters, contain 1 uppercase letter, 1 lowercase letter, 1 number and 1 special character.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        System.out.println("Entered Password: " + password);

        PasswordTextField.setText("");
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        UsernameLabel.setVisible(true);
        UsernameTextField.setVisible(true);
        PasswordLabel.setVisible(true);
        PasswordTextField.setVisible(true);
        JOptionPane.showMessageDialog(this, "Admin account selected!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        if (AdminButton.isSelected()) {
            if (UsernameTextField.getText().equals("") || PasswordTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Fill All Entries.", "Failure", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            User u = new User();
            if (u.isUsernameExists(UsernameTextField.getText())) {
                JOptionPane.showMessageDialog(this, "This username exits!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Please enter the verification code given to you to verify that you are an admin.",
                    "Authentication", JOptionPane.INFORMATION_MESSAGE);
            try {
                AuthenticationPageForAdmin authenticationPage = new AuthenticationPageForAdmin(
                        SurnameTextField.getText(),
                        UsernameTextField.getText(),
                        PasswordLabel.getText(),
                        PhoneNoTextField.getText(),
                        IDNumberLabel.getText());
                authenticationPage.setVisible(true);
                dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
            Admin admin = new Admin(PasswordTextField.getText(), UsernameTextField.getText());
            admin.insertAdmin(admin);
        } else if (CustomerButton.isSelected()) {
            if (NameTextField.getText().equals("") || SurnameTextField.getText().equals("") || UsernameTextField.getText().equals("") || PasswordTextField.getText().equals("") || PhoneNoTextField.getText().equals("") || IDNumberTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Fill All Entries.", "Failure", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            User u = new User();
            if (u.isUsernameExists(UsernameTextField.getText())) {
                JOptionPane.showMessageDialog(this, "This username exits!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Customer customer = new Customer(NameTextField.getText(), SurnameTextField.getText(), PasswordTextField.getText(), UsernameTextField.getText(), PhoneNoTextField.getText(), IDNumberTextField.getText());
            customer.insertCustomer(customer);
            JOptionPane.showMessageDialog(this, "Customer account created !");
        } else {
            JOptionPane.showMessageDialog(this, "Please choose an account type!", "Failure", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SwingUtilities.invokeLater(() -> {
            new StartScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccTypeLabel;
    private javax.swing.JRadioButton AdminButton;
    private javax.swing.JRadioButton CustomerButton;
    private javax.swing.JLabel IDNumberLabel;
    private javax.swing.JTextField IDNumberTextField;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel NameSurnameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JPasswordField PasswordSignInTextField;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JTextField PhoneNoTextField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JButton SignInButton;
    private javax.swing.JLabel SignInLabel;
    private javax.swing.JLayeredPane SignInLayeredPanel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel SignUpLabel;
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JTextField SurnameTextField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel UsernameLabel1;
    private javax.swing.JTextField UsernameSignInTextField;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
